# Geometry Related Services
geometry_circle:
  path: /v1/api/geometry/circle/{radius}
  controller: 'App\Controller\V1\Api\Geometry\CircleController::handleGET'
  methods: [GET]

geometry_triangle:
  path: /v1/api/geometry/triangle/{a}/{b}/{c}
  controller: 'App\Controller\V1\Api\Geometry\TriangleController::handleGET'
  methods: [GET]

geometry_sum_areas:
  path: /v1/api/geometry/sum/areas
  controller: 'App\Controller\V1\Api\Geometry\GeometryController::sumAreas'
  methods: [POST]

geometry_sum_diameters:
  path: /v1/api/geometry/sum/diameters
  controller: 'App\Controller\V1\Api\Geometry\GeometryController::sumDiameters'
  methods: [POST]

# Application Related Services
app_health:
  path: /v1/app/health
  controller: 'App\Controller\AppController::index'
  methods: [GET]